version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
      - node3
      - node4

  node1:
    build: .
    environment:
      - SERVER_PORT=8080
      - FILE_STORAGE_LOCATION=/app/storage
      - CLUSTER_NODES=http://node1:8080,http://node2:8080,http://node3:8080,http://node4:8080
    volumes:
      - ./storage/nodes:/app/storage

  node2:
    build: .
    environment:
      - SERVER_PORT=8080
      - FILE_STORAGE_LOCATION=/app/storage
      - CLUSTER_NODES=http://node1:8080,http://node2:8080,http://node3:8080,http://node4:8080
    volumes:
      - ./storage/nodes:/app/storage

  node3:
    build: .
    environment:
      - SERVER_PORT=8080
      - FILE_STORAGE_LOCATION=/app/storage
      - CLUSTER_NODES=http://node1:8080,http://node2:8080,http://node3:8080,http://node4:8080
    volumes:
      - ./storage/nodes:/app/storage

  node4:
    build: .
    environment:
      - SERVER_PORT=8080
      - FILE_STORAGE_LOCATION=/app/storage
      - CLUSTER_NODES=http://node1:8080,http://node2:8080,http://node3:8080,http://node4:8080
    volumes:
      - ./storage/nodes:/app/storage